/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ViewsRouteImport } from './routes/views'
import { Route as CyclesIndexRouteImport } from './routes/cycles/index'
import { Route as CyclesCycleIdRouteImport } from './routes/cycles/$cycleId'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as ApiV1BootstrapRouteImport } from './routes/api/v1/bootstrap'
import { Route as ApiV1PreferencesRouteImport } from './routes/api/v1/preferences'
import { Route as ApiV1SearchRouteImport } from './routes/api/v1/search'
import { Route as ApiV1BackgroundRunsIndexRouteImport } from './routes/api/v1/background-runs/index'
import { Route as ApiV1BackgroundRunsRunIdRouteImport } from './routes/api/v1/background-runs/$runId'
import { Route as ApiV1BackgroundRunsCurrentRouteImport } from './routes/api/v1/background-runs/current'
import { Route as ApiV1CyclesIndexRouteImport } from './routes/api/v1/cycles/index'
import { Route as ApiV1CyclesCycleIdRouteImport } from './routes/api/v1/cycles/$cycleId'
import { Route as ApiV1IssuesIndexRouteImport } from './routes/api/v1/issues/index'
import { Route as ApiV1IssuesIssueIdRouteImport } from './routes/api/v1/issues/$issueId'
import { Route as ApiV1IssuesBulkRouteImport } from './routes/api/v1/issues/bulk'
import { Route as ApiV1IssuesReorderRouteImport } from './routes/api/v1/issues/reorder'
import { Route as ApiV1LabelsIndexRouteImport } from './routes/api/v1/labels/index'
import { Route as ApiV1LabelsLabelIdRouteImport } from './routes/api/v1/labels/$labelId'
import { Route as ApiV1NotificationsIndexRouteImport } from './routes/api/v1/notifications/index'
import { Route as ApiV1NotificationsNotificationIdRouteImport } from './routes/api/v1/notifications/$notificationId'
import { Route as ApiV1ProjectsIndexRouteImport } from './routes/api/v1/projects/index'
import { Route as ApiV1ProjectsProjectIdRouteImport } from './routes/api/v1/projects/$projectId'
import { Route as ApiV1ViewsIndexRouteImport } from './routes/api/v1/views/index'
import { Route as ApiV1ViewsViewIdRouteImport } from './routes/api/v1/views/$viewId'
import { Route as ApiV1WorkflowStatesIndexRouteImport } from './routes/api/v1/workflow-states/index'
import { Route as ApiV1WorkflowStatesWorkflowStateIdRouteImport } from './routes/api/v1/workflow-states/$workflowStateId'
import { Route as ApiV1BackgroundRunsRunIdContinueRouteImport } from './routes/api/v1/background-runs/$runId/continue'
import { Route as ApiV1BackgroundRunsRunIdResumeRouteImport } from './routes/api/v1/background-runs/$runId/resume'
import { Route as ApiV1CyclesCycleIdStartRouteImport } from './routes/api/v1/cycles/$cycleId/start'
import { Route as ApiV1IssuesIssueIdNotesRouteImport } from './routes/api/v1/issues/$issueId/notes'
import { Route as ApiV1IssuesIssueIdRelationsRouteImport } from './routes/api/v1/issues/$issueId/relations'
import { Route as ApiV1IssuesIssueIdNotesNoteIdRouteImport } from './routes/api/v1/issues/$issueId/notes/$noteId'
import { Route as ApiV1IssuesIssueIdRelationsRelationIdRouteImport } from './routes/api/v1/issues/$issueId/relations/$relationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRoute = ViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesIndexRoute = CyclesIndexRouteImport.update({
  id: '/cycles/',
  path: '/cycles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesCycleIdRoute = CyclesCycleIdRouteImport.update({
  id: '/cycles/$cycleId',
  path: '/cycles/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BootstrapRoute = ApiV1BootstrapRouteImport.update({
  id: '/api/v1/bootstrap',
  path: '/api/v1/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PreferencesRoute = ApiV1PreferencesRouteImport.update({
  id: '/api/v1/preferences',
  path: '/api/v1/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/api/v1/search',
  path: '/api/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BackgroundRunsIndexRoute =
  ApiV1BackgroundRunsIndexRouteImport.update({
    id: '/api/v1/background-runs/',
    path: '/api/v1/background-runs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1BackgroundRunsRunIdRoute =
  ApiV1BackgroundRunsRunIdRouteImport.update({
    id: '/api/v1/background-runs/$runId',
    path: '/api/v1/background-runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1BackgroundRunsCurrentRoute =
  ApiV1BackgroundRunsCurrentRouteImport.update({
    id: '/api/v1/background-runs/current',
    path: '/api/v1/background-runs/current',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CyclesIndexRoute = ApiV1CyclesIndexRouteImport.update({
  id: '/api/v1/cycles/',
  path: '/api/v1/cycles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CyclesCycleIdRoute = ApiV1CyclesCycleIdRouteImport.update({
  id: '/api/v1/cycles/$cycleId',
  path: '/api/v1/cycles/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IssuesIndexRoute = ApiV1IssuesIndexRouteImport.update({
  id: '/api/v1/issues/',
  path: '/api/v1/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IssuesIssueIdRoute = ApiV1IssuesIssueIdRouteImport.update({
  id: '/api/v1/issues/$issueId',
  path: '/api/v1/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IssuesBulkRoute = ApiV1IssuesBulkRouteImport.update({
  id: '/api/v1/issues/bulk',
  path: '/api/v1/issues/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IssuesReorderRoute = ApiV1IssuesReorderRouteImport.update({
  id: '/api/v1/issues/reorder',
  path: '/api/v1/issues/reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LabelsIndexRoute = ApiV1LabelsIndexRouteImport.update({
  id: '/api/v1/labels/',
  path: '/api/v1/labels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LabelsLabelIdRoute = ApiV1LabelsLabelIdRouteImport.update({
  id: '/api/v1/labels/$labelId',
  path: '/api/v1/labels/$labelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsIndexRoute = ApiV1NotificationsIndexRouteImport.update({
  id: '/api/v1/notifications/',
  path: '/api/v1/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsNotificationIdRoute =
  ApiV1NotificationsNotificationIdRouteImport.update({
    id: '/api/v1/notifications/$notificationId',
    path: '/api/v1/notifications/$notificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsIndexRoute = ApiV1ProjectsIndexRouteImport.update({
  id: '/api/v1/projects/',
  path: '/api/v1/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsProjectIdRoute = ApiV1ProjectsProjectIdRouteImport.update({
  id: '/api/v1/projects/$projectId',
  path: '/api/v1/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ViewsIndexRoute = ApiV1ViewsIndexRouteImport.update({
  id: '/api/v1/views/',
  path: '/api/v1/views/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ViewsViewIdRoute = ApiV1ViewsViewIdRouteImport.update({
  id: '/api/v1/views/$viewId',
  path: '/api/v1/views/$viewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WorkflowStatesIndexRoute =
  ApiV1WorkflowStatesIndexRouteImport.update({
    id: '/api/v1/workflow-states/',
    path: '/api/v1/workflow-states/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkflowStatesWorkflowStateIdRoute =
  ApiV1WorkflowStatesWorkflowStateIdRouteImport.update({
    id: '/api/v1/workflow-states/$workflowStateId',
    path: '/api/v1/workflow-states/$workflowStateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1BackgroundRunsRunIdContinueRoute =
  ApiV1BackgroundRunsRunIdContinueRouteImport.update({
    id: '/continue',
    path: '/continue',
    getParentRoute: () => ApiV1BackgroundRunsRunIdRoute,
  } as any)
const ApiV1BackgroundRunsRunIdResumeRoute =
  ApiV1BackgroundRunsRunIdResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => ApiV1BackgroundRunsRunIdRoute,
  } as any)
const ApiV1CyclesCycleIdStartRoute = ApiV1CyclesCycleIdStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiV1CyclesCycleIdRoute,
} as any)
const ApiV1IssuesIssueIdNotesRoute = ApiV1IssuesIssueIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiV1IssuesIssueIdRoute,
} as any)
const ApiV1IssuesIssueIdRelationsRoute =
  ApiV1IssuesIssueIdRelationsRouteImport.update({
    id: '/relations',
    path: '/relations',
    getParentRoute: () => ApiV1IssuesIssueIdRoute,
  } as any)
const ApiV1IssuesIssueIdNotesNoteIdRoute =
  ApiV1IssuesIssueIdNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => ApiV1IssuesIssueIdNotesRoute,
  } as any)
const ApiV1IssuesIssueIdRelationsRelationIdRoute =
  ApiV1IssuesIssueIdRelationsRelationIdRouteImport.update({
    id: '/$relationId',
    path: '/$relationId',
    getParentRoute: () => ApiV1IssuesIssueIdRelationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/search': typeof SearchRoute
  '/views': typeof ViewsRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/cycles/': typeof CyclesIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/background-runs/$runId': typeof ApiV1BackgroundRunsRunIdRouteWithChildren
  '/api/v1/background-runs/current': typeof ApiV1BackgroundRunsCurrentRoute
  '/api/v1/cycles/$cycleId': typeof ApiV1CyclesCycleIdRouteWithChildren
  '/api/v1/issues/$issueId': typeof ApiV1IssuesIssueIdRouteWithChildren
  '/api/v1/issues/bulk': typeof ApiV1IssuesBulkRoute
  '/api/v1/issues/reorder': typeof ApiV1IssuesReorderRoute
  '/api/v1/labels/$labelId': typeof ApiV1LabelsLabelIdRoute
  '/api/v1/notifications/$notificationId': typeof ApiV1NotificationsNotificationIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRoute
  '/api/v1/views/$viewId': typeof ApiV1ViewsViewIdRoute
  '/api/v1/workflow-states/$workflowStateId': typeof ApiV1WorkflowStatesWorkflowStateIdRoute
  '/api/v1/background-runs/': typeof ApiV1BackgroundRunsIndexRoute
  '/api/v1/cycles/': typeof ApiV1CyclesIndexRoute
  '/api/v1/issues/': typeof ApiV1IssuesIndexRoute
  '/api/v1/labels/': typeof ApiV1LabelsIndexRoute
  '/api/v1/notifications/': typeof ApiV1NotificationsIndexRoute
  '/api/v1/projects/': typeof ApiV1ProjectsIndexRoute
  '/api/v1/views/': typeof ApiV1ViewsIndexRoute
  '/api/v1/workflow-states/': typeof ApiV1WorkflowStatesIndexRoute
  '/api/v1/background-runs/$runId/continue': typeof ApiV1BackgroundRunsRunIdContinueRoute
  '/api/v1/background-runs/$runId/resume': typeof ApiV1BackgroundRunsRunIdResumeRoute
  '/api/v1/cycles/$cycleId/start': typeof ApiV1CyclesCycleIdStartRoute
  '/api/v1/issues/$issueId/notes': typeof ApiV1IssuesIssueIdNotesRouteWithChildren
  '/api/v1/issues/$issueId/relations': typeof ApiV1IssuesIssueIdRelationsRouteWithChildren
  '/api/v1/issues/$issueId/notes/$noteId': typeof ApiV1IssuesIssueIdNotesNoteIdRoute
  '/api/v1/issues/$issueId/relations/$relationId': typeof ApiV1IssuesIssueIdRelationsRelationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/search': typeof SearchRoute
  '/views': typeof ViewsRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/cycles': typeof CyclesIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/background-runs/$runId': typeof ApiV1BackgroundRunsRunIdRouteWithChildren
  '/api/v1/background-runs/current': typeof ApiV1BackgroundRunsCurrentRoute
  '/api/v1/cycles/$cycleId': typeof ApiV1CyclesCycleIdRouteWithChildren
  '/api/v1/issues/$issueId': typeof ApiV1IssuesIssueIdRouteWithChildren
  '/api/v1/issues/bulk': typeof ApiV1IssuesBulkRoute
  '/api/v1/issues/reorder': typeof ApiV1IssuesReorderRoute
  '/api/v1/labels/$labelId': typeof ApiV1LabelsLabelIdRoute
  '/api/v1/notifications/$notificationId': typeof ApiV1NotificationsNotificationIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRoute
  '/api/v1/views/$viewId': typeof ApiV1ViewsViewIdRoute
  '/api/v1/workflow-states/$workflowStateId': typeof ApiV1WorkflowStatesWorkflowStateIdRoute
  '/api/v1/background-runs': typeof ApiV1BackgroundRunsIndexRoute
  '/api/v1/cycles': typeof ApiV1CyclesIndexRoute
  '/api/v1/issues': typeof ApiV1IssuesIndexRoute
  '/api/v1/labels': typeof ApiV1LabelsIndexRoute
  '/api/v1/notifications': typeof ApiV1NotificationsIndexRoute
  '/api/v1/projects': typeof ApiV1ProjectsIndexRoute
  '/api/v1/views': typeof ApiV1ViewsIndexRoute
  '/api/v1/workflow-states': typeof ApiV1WorkflowStatesIndexRoute
  '/api/v1/background-runs/$runId/continue': typeof ApiV1BackgroundRunsRunIdContinueRoute
  '/api/v1/background-runs/$runId/resume': typeof ApiV1BackgroundRunsRunIdResumeRoute
  '/api/v1/cycles/$cycleId/start': typeof ApiV1CyclesCycleIdStartRoute
  '/api/v1/issues/$issueId/notes': typeof ApiV1IssuesIssueIdNotesRouteWithChildren
  '/api/v1/issues/$issueId/relations': typeof ApiV1IssuesIssueIdRelationsRouteWithChildren
  '/api/v1/issues/$issueId/notes/$noteId': typeof ApiV1IssuesIssueIdNotesNoteIdRoute
  '/api/v1/issues/$issueId/relations/$relationId': typeof ApiV1IssuesIssueIdRelationsRelationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/search': typeof SearchRoute
  '/views': typeof ViewsRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/cycles/': typeof CyclesIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/preferences': typeof ApiV1PreferencesRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/background-runs/$runId': typeof ApiV1BackgroundRunsRunIdRouteWithChildren
  '/api/v1/background-runs/current': typeof ApiV1BackgroundRunsCurrentRoute
  '/api/v1/cycles/$cycleId': typeof ApiV1CyclesCycleIdRouteWithChildren
  '/api/v1/issues/$issueId': typeof ApiV1IssuesIssueIdRouteWithChildren
  '/api/v1/issues/bulk': typeof ApiV1IssuesBulkRoute
  '/api/v1/issues/reorder': typeof ApiV1IssuesReorderRoute
  '/api/v1/labels/$labelId': typeof ApiV1LabelsLabelIdRoute
  '/api/v1/notifications/$notificationId': typeof ApiV1NotificationsNotificationIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRoute
  '/api/v1/views/$viewId': typeof ApiV1ViewsViewIdRoute
  '/api/v1/workflow-states/$workflowStateId': typeof ApiV1WorkflowStatesWorkflowStateIdRoute
  '/api/v1/background-runs/': typeof ApiV1BackgroundRunsIndexRoute
  '/api/v1/cycles/': typeof ApiV1CyclesIndexRoute
  '/api/v1/issues/': typeof ApiV1IssuesIndexRoute
  '/api/v1/labels/': typeof ApiV1LabelsIndexRoute
  '/api/v1/notifications/': typeof ApiV1NotificationsIndexRoute
  '/api/v1/projects/': typeof ApiV1ProjectsIndexRoute
  '/api/v1/views/': typeof ApiV1ViewsIndexRoute
  '/api/v1/workflow-states/': typeof ApiV1WorkflowStatesIndexRoute
  '/api/v1/background-runs/$runId/continue': typeof ApiV1BackgroundRunsRunIdContinueRoute
  '/api/v1/background-runs/$runId/resume': typeof ApiV1BackgroundRunsRunIdResumeRoute
  '/api/v1/cycles/$cycleId/start': typeof ApiV1CyclesCycleIdStartRoute
  '/api/v1/issues/$issueId/notes': typeof ApiV1IssuesIssueIdNotesRouteWithChildren
  '/api/v1/issues/$issueId/relations': typeof ApiV1IssuesIssueIdRelationsRouteWithChildren
  '/api/v1/issues/$issueId/notes/$noteId': typeof ApiV1IssuesIssueIdNotesNoteIdRoute
  '/api/v1/issues/$issueId/relations/$relationId': typeof ApiV1IssuesIssueIdRelationsRelationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/search'
    | '/views'
    | '/cycles/$cycleId'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/settings/$section'
    | '/cycles/'
    | '/issues/'
    | '/projects/'
    | '/settings/'
    | '/api/v1/bootstrap'
    | '/api/v1/preferences'
    | '/api/v1/search'
    | '/api/v1/background-runs/$runId'
    | '/api/v1/background-runs/current'
    | '/api/v1/cycles/$cycleId'
    | '/api/v1/issues/$issueId'
    | '/api/v1/issues/bulk'
    | '/api/v1/issues/reorder'
    | '/api/v1/labels/$labelId'
    | '/api/v1/notifications/$notificationId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/views/$viewId'
    | '/api/v1/workflow-states/$workflowStateId'
    | '/api/v1/background-runs/'
    | '/api/v1/cycles/'
    | '/api/v1/issues/'
    | '/api/v1/labels/'
    | '/api/v1/notifications/'
    | '/api/v1/projects/'
    | '/api/v1/views/'
    | '/api/v1/workflow-states/'
    | '/api/v1/background-runs/$runId/continue'
    | '/api/v1/background-runs/$runId/resume'
    | '/api/v1/cycles/$cycleId/start'
    | '/api/v1/issues/$issueId/notes'
    | '/api/v1/issues/$issueId/relations'
    | '/api/v1/issues/$issueId/notes/$noteId'
    | '/api/v1/issues/$issueId/relations/$relationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/search'
    | '/views'
    | '/cycles/$cycleId'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/settings/$section'
    | '/cycles'
    | '/issues'
    | '/projects'
    | '/settings'
    | '/api/v1/bootstrap'
    | '/api/v1/preferences'
    | '/api/v1/search'
    | '/api/v1/background-runs/$runId'
    | '/api/v1/background-runs/current'
    | '/api/v1/cycles/$cycleId'
    | '/api/v1/issues/$issueId'
    | '/api/v1/issues/bulk'
    | '/api/v1/issues/reorder'
    | '/api/v1/labels/$labelId'
    | '/api/v1/notifications/$notificationId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/views/$viewId'
    | '/api/v1/workflow-states/$workflowStateId'
    | '/api/v1/background-runs'
    | '/api/v1/cycles'
    | '/api/v1/issues'
    | '/api/v1/labels'
    | '/api/v1/notifications'
    | '/api/v1/projects'
    | '/api/v1/views'
    | '/api/v1/workflow-states'
    | '/api/v1/background-runs/$runId/continue'
    | '/api/v1/background-runs/$runId/resume'
    | '/api/v1/cycles/$cycleId/start'
    | '/api/v1/issues/$issueId/notes'
    | '/api/v1/issues/$issueId/relations'
    | '/api/v1/issues/$issueId/notes/$noteId'
    | '/api/v1/issues/$issueId/relations/$relationId'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/search'
    | '/views'
    | '/cycles/$cycleId'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/settings/$section'
    | '/cycles/'
    | '/issues/'
    | '/projects/'
    | '/settings/'
    | '/api/v1/bootstrap'
    | '/api/v1/preferences'
    | '/api/v1/search'
    | '/api/v1/background-runs/$runId'
    | '/api/v1/background-runs/current'
    | '/api/v1/cycles/$cycleId'
    | '/api/v1/issues/$issueId'
    | '/api/v1/issues/bulk'
    | '/api/v1/issues/reorder'
    | '/api/v1/labels/$labelId'
    | '/api/v1/notifications/$notificationId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/views/$viewId'
    | '/api/v1/workflow-states/$workflowStateId'
    | '/api/v1/background-runs/'
    | '/api/v1/cycles/'
    | '/api/v1/issues/'
    | '/api/v1/labels/'
    | '/api/v1/notifications/'
    | '/api/v1/projects/'
    | '/api/v1/views/'
    | '/api/v1/workflow-states/'
    | '/api/v1/background-runs/$runId/continue'
    | '/api/v1/background-runs/$runId/resume'
    | '/api/v1/cycles/$cycleId/start'
    | '/api/v1/issues/$issueId/notes'
    | '/api/v1/issues/$issueId/relations'
    | '/api/v1/issues/$issueId/notes/$noteId'
    | '/api/v1/issues/$issueId/relations/$relationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  SearchRoute: typeof SearchRoute
  ViewsRoute: typeof ViewsRoute
  CyclesCycleIdRoute: typeof CyclesCycleIdRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SettingsSectionRoute: typeof SettingsSectionRoute
  CyclesIndexRoute: typeof CyclesIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiV1BootstrapRoute: typeof ApiV1BootstrapRoute
  ApiV1PreferencesRoute: typeof ApiV1PreferencesRoute
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  ApiV1BackgroundRunsRunIdRoute: typeof ApiV1BackgroundRunsRunIdRouteWithChildren
  ApiV1BackgroundRunsCurrentRoute: typeof ApiV1BackgroundRunsCurrentRoute
  ApiV1CyclesCycleIdRoute: typeof ApiV1CyclesCycleIdRouteWithChildren
  ApiV1IssuesIssueIdRoute: typeof ApiV1IssuesIssueIdRouteWithChildren
  ApiV1IssuesBulkRoute: typeof ApiV1IssuesBulkRoute
  ApiV1IssuesReorderRoute: typeof ApiV1IssuesReorderRoute
  ApiV1LabelsLabelIdRoute: typeof ApiV1LabelsLabelIdRoute
  ApiV1NotificationsNotificationIdRoute: typeof ApiV1NotificationsNotificationIdRoute
  ApiV1ProjectsProjectIdRoute: typeof ApiV1ProjectsProjectIdRoute
  ApiV1ViewsViewIdRoute: typeof ApiV1ViewsViewIdRoute
  ApiV1WorkflowStatesWorkflowStateIdRoute: typeof ApiV1WorkflowStatesWorkflowStateIdRoute
  ApiV1BackgroundRunsIndexRoute: typeof ApiV1BackgroundRunsIndexRoute
  ApiV1CyclesIndexRoute: typeof ApiV1CyclesIndexRoute
  ApiV1IssuesIndexRoute: typeof ApiV1IssuesIndexRoute
  ApiV1LabelsIndexRoute: typeof ApiV1LabelsIndexRoute
  ApiV1NotificationsIndexRoute: typeof ApiV1NotificationsIndexRoute
  ApiV1ProjectsIndexRoute: typeof ApiV1ProjectsIndexRoute
  ApiV1ViewsIndexRoute: typeof ApiV1ViewsIndexRoute
  ApiV1WorkflowStatesIndexRoute: typeof ApiV1WorkflowStatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/': {
      id: '/cycles/'
      path: '/cycles'
      fullPath: '/cycles/'
      preLoaderRoute: typeof CyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/$cycleId': {
      id: '/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof CyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bootstrap': {
      id: '/api/v1/bootstrap'
      path: '/api/v1/bootstrap'
      fullPath: '/api/v1/bootstrap'
      preLoaderRoute: typeof ApiV1BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/preferences': {
      id: '/api/v1/preferences'
      path: '/api/v1/preferences'
      fullPath: '/api/v1/preferences'
      preLoaderRoute: typeof ApiV1PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/api/v1/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/background-runs/': {
      id: '/api/v1/background-runs/'
      path: '/api/v1/background-runs'
      fullPath: '/api/v1/background-runs/'
      preLoaderRoute: typeof ApiV1BackgroundRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/background-runs/$runId': {
      id: '/api/v1/background-runs/$runId'
      path: '/api/v1/background-runs/$runId'
      fullPath: '/api/v1/background-runs/$runId'
      preLoaderRoute: typeof ApiV1BackgroundRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/background-runs/current': {
      id: '/api/v1/background-runs/current'
      path: '/api/v1/background-runs/current'
      fullPath: '/api/v1/background-runs/current'
      preLoaderRoute: typeof ApiV1BackgroundRunsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cycles/': {
      id: '/api/v1/cycles/'
      path: '/api/v1/cycles'
      fullPath: '/api/v1/cycles/'
      preLoaderRoute: typeof ApiV1CyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cycles/$cycleId': {
      id: '/api/v1/cycles/$cycleId'
      path: '/api/v1/cycles/$cycleId'
      fullPath: '/api/v1/cycles/$cycleId'
      preLoaderRoute: typeof ApiV1CyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/issues/': {
      id: '/api/v1/issues/'
      path: '/api/v1/issues'
      fullPath: '/api/v1/issues/'
      preLoaderRoute: typeof ApiV1IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/issues/$issueId': {
      id: '/api/v1/issues/$issueId'
      path: '/api/v1/issues/$issueId'
      fullPath: '/api/v1/issues/$issueId'
      preLoaderRoute: typeof ApiV1IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/issues/bulk': {
      id: '/api/v1/issues/bulk'
      path: '/api/v1/issues/bulk'
      fullPath: '/api/v1/issues/bulk'
      preLoaderRoute: typeof ApiV1IssuesBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/issues/reorder': {
      id: '/api/v1/issues/reorder'
      path: '/api/v1/issues/reorder'
      fullPath: '/api/v1/issues/reorder'
      preLoaderRoute: typeof ApiV1IssuesReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/labels/': {
      id: '/api/v1/labels/'
      path: '/api/v1/labels'
      fullPath: '/api/v1/labels/'
      preLoaderRoute: typeof ApiV1LabelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/labels/$labelId': {
      id: '/api/v1/labels/$labelId'
      path: '/api/v1/labels/$labelId'
      fullPath: '/api/v1/labels/$labelId'
      preLoaderRoute: typeof ApiV1LabelsLabelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/': {
      id: '/api/v1/notifications/'
      path: '/api/v1/notifications'
      fullPath: '/api/v1/notifications/'
      preLoaderRoute: typeof ApiV1NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/$notificationId': {
      id: '/api/v1/notifications/$notificationId'
      path: '/api/v1/notifications/$notificationId'
      fullPath: '/api/v1/notifications/$notificationId'
      preLoaderRoute: typeof ApiV1NotificationsNotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/': {
      id: '/api/v1/projects/'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects/'
      preLoaderRoute: typeof ApiV1ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId': {
      id: '/api/v1/projects/$projectId'
      path: '/api/v1/projects/$projectId'
      fullPath: '/api/v1/projects/$projectId'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/views/': {
      id: '/api/v1/views/'
      path: '/api/v1/views'
      fullPath: '/api/v1/views/'
      preLoaderRoute: typeof ApiV1ViewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/views/$viewId': {
      id: '/api/v1/views/$viewId'
      path: '/api/v1/views/$viewId'
      fullPath: '/api/v1/views/$viewId'
      preLoaderRoute: typeof ApiV1ViewsViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workflow-states/': {
      id: '/api/v1/workflow-states/'
      path: '/api/v1/workflow-states'
      fullPath: '/api/v1/workflow-states/'
      preLoaderRoute: typeof ApiV1WorkflowStatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workflow-states/$workflowStateId': {
      id: '/api/v1/workflow-states/$workflowStateId'
      path: '/api/v1/workflow-states/$workflowStateId'
      fullPath: '/api/v1/workflow-states/$workflowStateId'
      preLoaderRoute: typeof ApiV1WorkflowStatesWorkflowStateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/background-runs/$runId/continue': {
      id: '/api/v1/background-runs/$runId/continue'
      path: '/continue'
      fullPath: '/api/v1/background-runs/$runId/continue'
      preLoaderRoute: typeof ApiV1BackgroundRunsRunIdContinueRouteImport
      parentRoute: typeof ApiV1BackgroundRunsRunIdRoute
    }
    '/api/v1/background-runs/$runId/resume': {
      id: '/api/v1/background-runs/$runId/resume'
      path: '/resume'
      fullPath: '/api/v1/background-runs/$runId/resume'
      preLoaderRoute: typeof ApiV1BackgroundRunsRunIdResumeRouteImport
      parentRoute: typeof ApiV1BackgroundRunsRunIdRoute
    }
    '/api/v1/cycles/$cycleId/start': {
      id: '/api/v1/cycles/$cycleId/start'
      path: '/start'
      fullPath: '/api/v1/cycles/$cycleId/start'
      preLoaderRoute: typeof ApiV1CyclesCycleIdStartRouteImport
      parentRoute: typeof ApiV1CyclesCycleIdRoute
    }
    '/api/v1/issues/$issueId/notes': {
      id: '/api/v1/issues/$issueId/notes'
      path: '/notes'
      fullPath: '/api/v1/issues/$issueId/notes'
      preLoaderRoute: typeof ApiV1IssuesIssueIdNotesRouteImport
      parentRoute: typeof ApiV1IssuesIssueIdRoute
    }
    '/api/v1/issues/$issueId/relations': {
      id: '/api/v1/issues/$issueId/relations'
      path: '/relations'
      fullPath: '/api/v1/issues/$issueId/relations'
      preLoaderRoute: typeof ApiV1IssuesIssueIdRelationsRouteImport
      parentRoute: typeof ApiV1IssuesIssueIdRoute
    }
    '/api/v1/issues/$issueId/notes/$noteId': {
      id: '/api/v1/issues/$issueId/notes/$noteId'
      path: '/$noteId'
      fullPath: '/api/v1/issues/$issueId/notes/$noteId'
      preLoaderRoute: typeof ApiV1IssuesIssueIdNotesNoteIdRouteImport
      parentRoute: typeof ApiV1IssuesIssueIdNotesRoute
    }
    '/api/v1/issues/$issueId/relations/$relationId': {
      id: '/api/v1/issues/$issueId/relations/$relationId'
      path: '/$relationId'
      fullPath: '/api/v1/issues/$issueId/relations/$relationId'
      preLoaderRoute: typeof ApiV1IssuesIssueIdRelationsRelationIdRouteImport
      parentRoute: typeof ApiV1IssuesIssueIdRelationsRoute
    }
  }
}

interface ApiV1BackgroundRunsRunIdRouteChildren {
  ApiV1BackgroundRunsRunIdContinueRoute: typeof ApiV1BackgroundRunsRunIdContinueRoute
  ApiV1BackgroundRunsRunIdResumeRoute: typeof ApiV1BackgroundRunsRunIdResumeRoute
}

const ApiV1BackgroundRunsRunIdRouteChildren: ApiV1BackgroundRunsRunIdRouteChildren =
  {
    ApiV1BackgroundRunsRunIdContinueRoute:
      ApiV1BackgroundRunsRunIdContinueRoute,
    ApiV1BackgroundRunsRunIdResumeRoute: ApiV1BackgroundRunsRunIdResumeRoute,
  }

const ApiV1BackgroundRunsRunIdRouteWithChildren =
  ApiV1BackgroundRunsRunIdRoute._addFileChildren(
    ApiV1BackgroundRunsRunIdRouteChildren,
  )

interface ApiV1CyclesCycleIdRouteChildren {
  ApiV1CyclesCycleIdStartRoute: typeof ApiV1CyclesCycleIdStartRoute
}

const ApiV1CyclesCycleIdRouteChildren: ApiV1CyclesCycleIdRouteChildren = {
  ApiV1CyclesCycleIdStartRoute: ApiV1CyclesCycleIdStartRoute,
}

const ApiV1CyclesCycleIdRouteWithChildren =
  ApiV1CyclesCycleIdRoute._addFileChildren(ApiV1CyclesCycleIdRouteChildren)

interface ApiV1IssuesIssueIdNotesRouteChildren {
  ApiV1IssuesIssueIdNotesNoteIdRoute: typeof ApiV1IssuesIssueIdNotesNoteIdRoute
}

const ApiV1IssuesIssueIdNotesRouteChildren: ApiV1IssuesIssueIdNotesRouteChildren =
  {
    ApiV1IssuesIssueIdNotesNoteIdRoute: ApiV1IssuesIssueIdNotesNoteIdRoute,
  }

const ApiV1IssuesIssueIdNotesRouteWithChildren =
  ApiV1IssuesIssueIdNotesRoute._addFileChildren(
    ApiV1IssuesIssueIdNotesRouteChildren,
  )

interface ApiV1IssuesIssueIdRelationsRouteChildren {
  ApiV1IssuesIssueIdRelationsRelationIdRoute: typeof ApiV1IssuesIssueIdRelationsRelationIdRoute
}

const ApiV1IssuesIssueIdRelationsRouteChildren: ApiV1IssuesIssueIdRelationsRouteChildren =
  {
    ApiV1IssuesIssueIdRelationsRelationIdRoute:
      ApiV1IssuesIssueIdRelationsRelationIdRoute,
  }

const ApiV1IssuesIssueIdRelationsRouteWithChildren =
  ApiV1IssuesIssueIdRelationsRoute._addFileChildren(
    ApiV1IssuesIssueIdRelationsRouteChildren,
  )

interface ApiV1IssuesIssueIdRouteChildren {
  ApiV1IssuesIssueIdNotesRoute: typeof ApiV1IssuesIssueIdNotesRouteWithChildren
  ApiV1IssuesIssueIdRelationsRoute: typeof ApiV1IssuesIssueIdRelationsRouteWithChildren
}

const ApiV1IssuesIssueIdRouteChildren: ApiV1IssuesIssueIdRouteChildren = {
  ApiV1IssuesIssueIdNotesRoute: ApiV1IssuesIssueIdNotesRouteWithChildren,
  ApiV1IssuesIssueIdRelationsRoute:
    ApiV1IssuesIssueIdRelationsRouteWithChildren,
}

const ApiV1IssuesIssueIdRouteWithChildren =
  ApiV1IssuesIssueIdRoute._addFileChildren(ApiV1IssuesIssueIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  SearchRoute: SearchRoute,
  ViewsRoute: ViewsRoute,
  CyclesCycleIdRoute: CyclesCycleIdRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SettingsSectionRoute: SettingsSectionRoute,
  CyclesIndexRoute: CyclesIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiV1BootstrapRoute: ApiV1BootstrapRoute,
  ApiV1PreferencesRoute: ApiV1PreferencesRoute,
  ApiV1SearchRoute: ApiV1SearchRoute,
  ApiV1BackgroundRunsRunIdRoute: ApiV1BackgroundRunsRunIdRouteWithChildren,
  ApiV1BackgroundRunsCurrentRoute: ApiV1BackgroundRunsCurrentRoute,
  ApiV1CyclesCycleIdRoute: ApiV1CyclesCycleIdRouteWithChildren,
  ApiV1IssuesIssueIdRoute: ApiV1IssuesIssueIdRouteWithChildren,
  ApiV1IssuesBulkRoute: ApiV1IssuesBulkRoute,
  ApiV1IssuesReorderRoute: ApiV1IssuesReorderRoute,
  ApiV1LabelsLabelIdRoute: ApiV1LabelsLabelIdRoute,
  ApiV1NotificationsNotificationIdRoute: ApiV1NotificationsNotificationIdRoute,
  ApiV1ProjectsProjectIdRoute: ApiV1ProjectsProjectIdRoute,
  ApiV1ViewsViewIdRoute: ApiV1ViewsViewIdRoute,
  ApiV1WorkflowStatesWorkflowStateIdRoute:
    ApiV1WorkflowStatesWorkflowStateIdRoute,
  ApiV1BackgroundRunsIndexRoute: ApiV1BackgroundRunsIndexRoute,
  ApiV1CyclesIndexRoute: ApiV1CyclesIndexRoute,
  ApiV1IssuesIndexRoute: ApiV1IssuesIndexRoute,
  ApiV1LabelsIndexRoute: ApiV1LabelsIndexRoute,
  ApiV1NotificationsIndexRoute: ApiV1NotificationsIndexRoute,
  ApiV1ProjectsIndexRoute: ApiV1ProjectsIndexRoute,
  ApiV1ViewsIndexRoute: ApiV1ViewsIndexRoute,
  ApiV1WorkflowStatesIndexRoute: ApiV1WorkflowStatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
